services:
  # Frontend React
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://host.docker.internal:8000/api
    volumes:
      # Para desenvolvimento - monta o código fonte
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
